### ISSUE TITLE
Learning resources

### ISSUE THREAD

**Issue by bantolov** [Rhetos/Rhetos#118]
This is a high-level topic created for discussion and progress tracking on the "Learning resources" goal from [Rhetos roadmap](https://github.com/Rhetos/Rhetos/wiki/Rhetos-platform-roadmap).

Some of the related tasks can be found in the issues list under [documentation](https://github.com/Rhetos/Rhetos/labels/documentation) tag.

This project has been closed, since planned documentation for this phase has been published. Remaining topics that require more documentation are moved to stand-alone issues with [documentation label](https://github.com/Rhetos/Rhetos/labels/documentation).

## About the project

* [x] What is Rhetos: [wiki](https://github.com/Rhetos/Rhetos/wiki/What-is-Rhetos)
* [x] Where to find help: [homepage](https://github.com/Rhetos/Rhetos/wiki), [issues](https://github.com/Rhetos/Rhetos/issues)

## Application development tutorials

Create your first Rhetos application:

* [x] Development environment setup: [prerequisites](https://github.com/Rhetos/Rhetos/wiki/Prerequisites), [setup](https://github.com/Rhetos/Rhetos/wiki/Development-Environment-Setup)
* [x] Quick-start guide with an example [Create your first Rhetos application](https://github.com/Rhetos/Rhetos/wiki/Create-your-first-Rhetos-application).
* [x] Rhetos DSL: [syntax](https://github.com/Rhetos/Rhetos/wiki/Rhetos-DSL-syntax), [coding standard](https://github.com/Rhetos/Rhetos/wiki/Rhetos-coding-standard)

Basic DSL concepts:

* [x] Data model and relationships: [tutorial](https://github.com/Rhetos/Rhetos/wiki/Data-structures-and-relationships)
* [x] Read-only data structures: [tutorial](https://github.com/Rhetos/Rhetos/wiki/Read-only-data-structures)
* [x] Simple business rules: [simple business rules](https://github.com/Rhetos/Rhetos/wiki/Implementing-simple-business-rules), [examples in unit tests](https://github.com/Rhetos/Rhetos/blob/master/CommonConcepts/CommonConceptsTest/DslScripts/SimpleBusinessLogic.rhe)
  * [x] Complete the wiki page on Simple business rules.
* [x] Domain Object Model: [tutorial](https://github.com/Rhetos/Rhetos/wiki/Using-the-Domain-Object-Model)
  * [x] Describe the most important classes in the generated object model.
  * [x] Example: Playground console app with ConsoleDump NuGet.
* [x] Filters: [tutorial](https://github.com/Rhetos/Rhetos/wiki/Filters-and-other-read-methods)
* [x] Validations: [tutorial](https://github.com/Rhetos/Rhetos/wiki/Data-validations)
* [x] Persisting the computed data (in progress): [tutorial](https://github.com/Rhetos/Rhetos/wiki/Persisting-the-computed-data) => #312

Extending DSL:

* [x] Develop macro concepts: [tutorial](https://github.com/Rhetos/Rhetos/wiki/Rhetos-concept-development)
* [x] Develop a code generator: [tutorial](https://github.com/Rhetos/Rhetos/wiki/Rhetos-concept-development)

Implementing business processes:

* [x] Tutorial "Implementing business processes", with 2 typical examples: updating status and accumulating amounts. => #311, #289
* [x] Event sourcing => #311
* [x] Entity inheritance: [polymorphic](https://github.com/Rhetos/Rhetos/wiki/Polymorphic-concept)

Other:

* [x] Overview of all Rhetos concepts: [wiki](https://github.com/Rhetos/Rhetos/wiki/List-of-DSL-concepts-in-CommonConcepts)
* [x] Overview of useful Rhetos server components and tools (for example, GenericRepository) => #317
* [x] Low-level object model concepts: [wiki](https://github.com/Rhetos/Rhetos/wiki/Low-level-object-model-concepts)
* [x] Direct control of database structure: [database](https://github.com/Rhetos/Rhetos/wiki/Database-objects), [sqlobject](https://github.com/Rhetos/Rhetos/wiki/SqlObject-concept)
  * [x] LegacyEntity concept => #309
* [x] Temporal data and change history: [wiki](https://github.com/Rhetos/Rhetos/wiki/Temporal-data-and-change-history)
* [x] Implementing business logic in a separate library: [action](https://github.com/Rhetos/Rhetos/wiki/Action-concept), [demo for dom-independent](https://github.com/Rhetos/Bookstore)
* [x] Full-text search: [dsl examples](https://github.com/Rhetos/Rhetos/blob/master/CommonConcepts/CommonConceptsTest/DslScripts/FullTextSearchTest.rhe), [code examples](https://github.com/Rhetos/Rhetos/blob/master/CommonConcepts/CommonConceptsTest/CommonConcepts.Test/FullTextSearchTest.cs)
  * [x] Tutorial => #316

## Fundamentals

* [x] Web API - REST: [documentation](https://github.com/Rhetos/RestGenerator/blob/master/Readme.md)
* [x] Authorization and authentication
  * [x] Basic permissions (Claims): [authorization](https://github.com/Rhetos/Rhetos/wiki/User-authentication-and-authorization), [claims](https://github.com/Rhetos/Rhetos/wiki/Basic-permissions)
  * [x] Row permissions: [authorization](https://github.com/Rhetos/Rhetos/wiki/User-authentication-and-authorization), [rowpermissions](https://github.com/Rhetos/Rhetos/wiki/RowPermissions-concept)
  * [x] User authentication: [authentication](https://github.com/Rhetos/Rhetos/wiki/User-authentication-and-authorization)
  * [x] Custom authentication plugin: [wiki](https://github.com/Rhetos/Rhetos/wiki/Implementing-Rhetos-authentication-plugins)
* [x] Migrating the application data when changing the database structure: [datamigration](https://github.com/Rhetos/Rhetos/wiki/Data-migration), [afterdeploy](https://github.com/Rhetos/AfterDeploy)
* [x] Unit testing: [demo](https://github.com/Rhetos/Bookstore#unit-testing) with standard unit tests and integration tests
  * [x] Walkthrough => #314
* [x] Debugging: [tutorial](https://github.com/Rhetos/Rhetos/wiki/Debugging)
* [x] Rhetos ecosystem - Available plugins: [wiki](https://github.com/Rhetos/Rhetos/wiki#recommended-plugins)
* [x] System Logging (NLog): [wiki](https://github.com/Rhetos/Rhetos/wiki/Logging)
* [x] Deploying Rhetos applications => #313
* [x] Internationalization and labels: [i18nformatter](https://github.com/Rhetos/I18NFormatter/blob/master/Readme.md), [mvcmodelgenerator](https://github.com/Rhetos/MvcModelGenerator)
* [x] Reporting => #315

## Sample projects with best practices

* [x] [Bookstore](https://github.com/Rhetos/Bookstore) demo application is created. We want to expand it with additional design patterns and components.
* [x] Rhetos DSL packages with new DSL concepts: [tutorial](https://github.com/Rhetos/Rhetos/wiki/Creating-Rhetos-package).

## Quick startup for new projects

* [x] New build process with Rhetos CLI (#49) allows quick-start by simply adding Rhetos NuGet to new web application.

## Issues database

* [x] We are redirecting all questions and discussions to the Rhetos [Issues list](https://github.com/Rhetos/Rhetos/issues). In a long run it will server as a searchable FAQ collection.

**Comment by bantolov** [comment]
Here is a list of new wiki articles written since this issue was created, as some kind of a progress report for the related roadmap goal:

* Tutorial [Create your first Rhetos application](https://github.com/Rhetos/Rhetos/wiki/Create-your-first-Rhetos-application) 
* Tutorial [Read only data structures](https://github.com/Rhetos/Rhetos/wiki/Read-only-data-structures) - Browse, SqlQueryable, Computed
* Tutorial [Filters and other read methods](https://github.com/Rhetos/Rhetos/wiki/Filters-and-other-read-methods) - FilterBy, ComposableFilterBy, ItemFilter, Query
* New chapters in tutorial [Using the Domain Object Model](https://github.com/Rhetos/Rhetos/wiki/Using-the-Domain-Object-Model)  
    * Understanding the generated object model
    * Many new examples
* New chapters in tutorial [Data migration](https://github.com/Rhetos/Rhetos/wiki/Data-migration)
    * Improved examples with step-by-step walkthrough
    * Issue with unique constraint
* New chapters in [Implementing simple business rules](https://github.com/Rhetos/Rhetos/wiki/Implementing-simple-business-rules)
    * Additional constraints
    * Deny data modifications
    * Automatically generated data
    * Logging data changes and auditing
    * Other features
* New chapters in [Persisting the computed data](https://github.com/Rhetos/Rhetos/wiki/Persisting-the-computed-data)
    * Automatic recompute on deployment
* Tutorial [Debugging](https://github.com/Rhetos/Rhetos/wiki/Debugging)
* Tutorial [Logging](https://github.com/Rhetos/Rhetos/wiki/Logging)
* Tutorial [Creating Rhetos package](https://github.com/Rhetos/Rhetos/wiki/Creating-Rhetos-package)
* Tutorial [Rhetos concept development](https://github.com/Rhetos/Rhetos/wiki/Rhetos-concept-development)
* [Release management](https://github.com/Rhetos/Rhetos/wiki/Release-management)
* [Setting up Rhetos for HTTPS](https://github.com/Rhetos/Rhetos/wiki/Setting-up-Rhetos-for-HTTPS)
* [List of DSL concepts in CommonConcepts](https://github.com/Rhetos/Rhetos/wiki/List-of-DSL-concepts-in-CommonConcepts)
* [Low level object model concepts](https://github.com/Rhetos/Rhetos/wiki/Low-level-object-model-concepts) - SaveMethod, RepositoryUses, RepositoryMember
* [Temporal data and change history](https://github.com/Rhetos/Rhetos/wiki/Temporal-data-and-change-history) - History
* [Using Postman with Rhetos](https://github.com/Rhetos/Rhetos/wiki/Using-Postman-with-Rhetos)

**Comment by bantolov** [comment]
New wiki article:
* Tutorial [Data validations](https://github.com/Rhetos/Rhetos/wiki/Data-validations)

**Comment by bantolov** [comment]
New documentation:

* Completed [List of DSL concepts in CommonConcepts](https://github.com/Rhetos/Rhetos/wiki/List-of-DSL-concepts-in-CommonConcepts)
* [Simple read only entities and codetables (Hardcoded concept)](https://github.com/Rhetos/Rhetos/wiki/simple-read-only-entities-and-codetables)
* [How to upgrade your application to a new version of Rhetos](https://github.com/Rhetos/Rhetos/wiki/Upgrade-Rhetos-version)
* New section in Create your first Rhetos application: [A more complex build process example](https://github.com/Rhetos/Rhetos/wiki/Create-your-first-Rhetos-application#a-more-complex-build-process-example)
* New section in Rhetos concept development: [Dependency between code generators](https://github.com/Rhetos/Rhetos/wiki/Rhetos-concept-development#dependency-between-code-generators)
* New sections in SqlObject tutorial: [Create a custom object in the database](https://github.com/Rhetos/Rhetos/wiki/SqlObject-concept#create-a-custom-object-in-the-database), Troubleshooting: Fixing an incorrect removal script

**Comment by bantolov** [comment]
Closing this project, since all planned documentation for this phase has been published.

**Remaining topics** that require further documentation are moved to stand-alone issues with [documentation label](https://github.com/Rhetos/Rhetos/labels/documentation).
